package com.example.yamiyukisenpai.a3imageswitcher;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.view.animation.AnimationUtils;
import android.widget.Button;
import android.widget.ImageSwitcher;
import android.widget.ImageView;
import android.widget.ViewSwitcher;

import java.util.Random;

import static android.widget.ImageView.ScaleType.CENTER_INSIDE;
import static android.widget.ImageView.ScaleType.FIT_XY;

public class MainActivity extends AppCompatActivity {

    ImageSwitcher sample_image_switcher;
    Button next_button;
    // An array of images
    int img_arr[] = {R.drawable.tali_me3, R.drawable.kubuntu_desktop, R.drawable.ts_fearless,
            R.drawable.liara_me3, R.drawable.flash_supergirl};
    Random rand = new Random();
    int curr_index;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        curr_index = 0;
        sample_image_switcher = findViewById(R.id.rand_imageSwitcher);
        // Setting up Image View
        sample_image_switcher.setFactory(new ViewSwitcher.ViewFactory() {
            @Override
            public View makeView() {
                ImageView rand_image = new ImageView(getApplicationContext());
                rand_image.setScaleType(CENTER_INSIDE);
                return rand_image;
            }
        });
        // Setting the first image in the array as the image to be show when app is first
        // launched
        sample_image_switcher.setImageResource(img_arr[curr_index]);
        // Added an animation for image transition
        sample_image_switcher.setInAnimation
                (AnimationUtils.loadAnimation(this, android.R.anim.fade_in));
        
        next_button = findViewById(R.id.next_button);
        next_button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                int new_index = curr_index;
                while (new_index == curr_index) {
                    // Random index values generated by random number generator
                    // Have to make sure that the number generator won't generate the same values
                    //  As the current index
                    curr_index = rand.nextInt(img_arr.length);
                }
                //sample_background_image_switcher.setImageResource(img_arr[curr_index]);
                sample_image_switcher.setImageResource(img_arr[curr_index]);
            }
        });


    }
}

